export const cases = {
  carupgrade: {
    name: 'Carupgrade',
    industry: 'Mobilt autoværksted',
    summary: 'En serviceorienteret hjemmeside, der gør et mobilt værksted let at forstå og nemt at bestille.',
    challenge: 'Carupgrade løser både service, diagnose og reparation hos kunden. Hjemmesiden skulle forklare den anderledes værkstedsmodel hurtigt og skabe en tydelig vej til et tilbud.',
    decisions: [
      'En direkte hero med den mobile service som første budskab.',
      'En konkret proces fra opgavebeskrivelse til udført reparation.',
      'Services, dækningsområde og kontakt samlet i en enkel kunderejse.',
    ],
    deliverables: ['Responsivt webdesign', 'Servicestruktur', 'Tilbudsformular', 'Trustpilot-integration', 'Hosting og drift'],
    url: 'https://carupgrade.dk/',
    desktop: '/cases/carupgrade-desktop.webp',
    mobile: '/cases/carupgrade-mobile.webp',
    desktopSize: { width: 1425, height: 7771 },
    mobileSize: { width: 375, height: 13494 },
  },
  lepas: {
    name: 'Lepas Dressage',
    industry: 'Opstaldning og dressur',
    summary: 'Et roligt, billedbåret website, der samler opstaldning, faciliteter og dressurfaglighed i en tydelig oplevelse.',
    challenge: 'Lepas Dressage har flere beslægtede ydelser, men opstaldning er den vigtigste indgang. Siden skulle skabe ro omkring tilbuddet og gøre priser, faciliteter og kontakt konkrete.',
    decisions: [
      'Opstaldning er prioriteret som sidens primære handling.',
      'Rigtige hestebilleder bærer den visuelle fortælling.',
      'Priser, faciliteter og daglige rutiner er gjort nemme at afkode.',
    ],
    deliverables: ['Visuel retning', 'Responsivt webdesign', 'Ydelsessider', 'Kontaktflow', 'Hosting og drift'],
    url: 'https://lepas-dressage.vercel.app/',
    desktop: '/cases/lepas-dressage-desktop.webp',
    mobile: '/cases/lepas-dressage-mobile.webp',
    desktopSize: { width: 1425, height: 4581 },
    mobileSize: { width: 375, height: 6486 },
  },
}
